# Generated by Django 5.0.3 on 2024-04-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_usercard_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='trade_request_status',
        ),
        migrations.AddField(
            model_name='decks',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='playerRequesting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Cancelled'), ('p', 'Pending'), ('f', 'Finished')], default='p', help_text='Trade Status', max_length=1),
        ),
        migrations.AddField(
            model_name='traderesponse',
            name='playerResponding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cards.card'),
        ),
    ]
