# Generated by Django 5.0.3 on 2024-04-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_traderequest_trade_request_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeStatus',
        ),
    ]
