# Generated by Django 5.0.3 on 2024-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_delete_tradestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_value', 'card_title']},
        ),
    ]
