# Generated by Django 4.2.11 on 2024-04-29 01:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_requestedcard_trade_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the card', null=True, upload_to='card_images/'),
        ),
        migrations.AlterField(
            model_name='offeredcard',
            name='offered_card_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Offered Card', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offeredcard',
            name='trade_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.traderequest'),
        ),
        migrations.AlterField(
            model_name='requestedcard',
            name='requested_card_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Enter the quantity of requested cards (must be greater than 0)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='requestedcard',
            name='trade_request_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.traderequest'),
        ),
    ]
